package com.javaee.ebook1.mybatis.entity;

import java.io.Serializable;

public class Books implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.bid
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.book_name
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.author
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.descr
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    private String descr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.book_cover
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    private String bookCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.file
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.folder
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    private String folder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.page
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    private Integer page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.bid
     *
     * @return the value of books.bid
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.bid
     *
     * @param bid the value for books.bid
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.book_name
     *
     * @return the value of books.book_name
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.book_name
     *
     * @param bookName the value for books.book_name
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.author
     *
     * @return the value of books.author
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.author
     *
     * @param author the value for books.author
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.descr
     *
     * @return the value of books.descr
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.descr
     *
     * @param descr the value for books.descr
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.book_cover
     *
     * @return the value of books.book_cover
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public String getBookCover() {
        return bookCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.book_cover
     *
     * @param bookCover the value for books.book_cover
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public void setBookCover(String bookCover) {
        this.bookCover = bookCover == null ? null : bookCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.file
     *
     * @return the value of books.file
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.file
     *
     * @param file the value for books.file
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.folder
     *
     * @return the value of books.folder
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public String getFolder() {
        return folder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.folder
     *
     * @param folder the value for books.folder
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public void setFolder(String folder) {
        this.folder = folder == null ? null : folder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.page
     *
     * @return the value of books.page
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public Integer getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.page
     *
     * @param page the value for books.page
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    public void setPage(Integer page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bid=").append(bid);
        sb.append(", bookName=").append(bookName);
        sb.append(", author=").append(author);
        sb.append(", descr=").append(descr);
        sb.append(", bookCover=").append(bookCover);
        sb.append(", file=").append(file);
        sb.append(", folder=").append(folder);
        sb.append(", page=").append(page);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}