package com.javaee.ebook1.mybatis.dao;

import com.javaee.ebook1.mybatis.entity.Books;
import com.javaee.ebook1.mybatis.entity.BooksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BooksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    long countByExample(BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int deleteByExample(BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int deleteByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int insert(Books record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int insertSelective(Books record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    List<Books> selectByExample(BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    Books selectByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int updateByExampleSelective(@Param("record") Books record, @Param("example") BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int updateByExample(@Param("record") Books record, @Param("example") BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int updateByPrimaryKeySelective(Books record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int updateByPrimaryKey(Books record);
}