package com.javaee.ebook1.mybatis.dao;

import com.javaee.ebook1.mybatis.entity.Log;
import com.javaee.ebook1.mybatis.entity.LogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    long countByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int deleteByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int insertSelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    List<Log> selectByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int updateByExampleSelective(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Wed Apr 14 14:41:41 CST 2021
     */
    int updateByExample(@Param("record") Log record, @Param("example") LogExample example);
}